- hosts: terraform_ansible
  tasks:
    - name: Installing python3 & virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: Installing dependencies with pip (Django and DjangoREST)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework

    # - name: Creating a new file
    #   copy:
    #     dest: /home/ubuntu/index.html
    #     content: <h1>Eu te amo minha linda <3</h1>
    # - name: Creating HTTP server
    #   shell: "nohup busybox httpd -f -p 8080 &"
